### PR TITLE
updated IT8665E to 4 Fans

### PR DESCRIPTION
**Pull request by thegame4craft**
As you've written in the pull request in Librehardwaremonitor/librehardwaremonitor i changed it to 4 fans & 4 controls.

See https://github.com/frankcrawford/it87/blob/master/Sensors%20configs/ASUS_PRIME_B450-PLUS.conf#L33-L36 for more references

### CODE REVIEW

**Comment by Rem0o** [comment]
@thegame4craft  from the specsheets, the IT8665E seems to have more than 4 fan channels: 
https://github.com/a1wong/it87/blob/master/ITE_Register_map.pdf

I get some users reporting a working channel has disapeared: https://github.com/Rem0o/FanControl.Releases/issues/2756#issuecomment-2381291753

What's up with that 4 fans change?

**Comment by thegame4craft** [comment]
For me on github mobile it looks like the chip supports up to 6 fans. Is that true?

**Comment by thegame4craft** [comment]
If you're looking at this document it seems that that chip supports 6 sensors however on my mainboard no 5 is not connected or disabled

https://github.com/frankcrawford/it87/blob/master/Sensors%20configs%2FASUS_PRIME_B450-PLUS.conf

**Comment by Rem0o** [comment]
@thegame4craft  your motherboard may or may not use all the channels offered by the chip, but that same chip on an other board may use 5 or 6 channels.  The LPC code must reflect the chip, not how many channel a specific motherboard uses.   Some users were using 5 channels just fine before this change.

**Comment by thegame4craft** [comment]
@Rem0o i made a pullrequest to librehardwaremonitor https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1484

i think it will take a few weeks until it gets merged, because the last time i made one, it took about 2w

**Pull request merged**
